apiVersion: v1
kind: Service
metadata:
  name: cloud-db-service
spec:
  type: LoadBalancer
  selector:
    app: cloud-db-app
  ports:
    - protocol: TCP
      port: 80            # 对外暴露的端口
      targetPort: 3000    # 容器中 Node.js 应用监听的端口
